export const CatalogoBeneficios = [
  { value: "", label: "Selecione" },
  {
    value: "601",
    label:
      "PPR - Planos individuais de poupança-reforma (n.º 2 do artigo 21.º do EBF)",
  },
  {
    value: "602",
    label:
      "Contribuições individuais para fundos de pensões, para associações mutualistas e outros regimes complementares de segurança social (artigo 16.ºdo EBF)",
  },
  {
    value: "603",
    label:
      "Regime Público de Capitalização - valores aplicados em contas individuais geridas em regime público de capitalização (artigo 17.º do EBF)",
  },
  {
    value: "604",
    label:
      "Contribuições, pagas por sujeitos passivos com deficiência, para reforma por velhice (n.º 3 do artigo 87.º do Código do IRS)",
  },
  {
    value: "605",
    label:
      "Prémios de seguros de vida despendidos por pessoas com deficiência, bem como as contribuições pagas a associações mutualistas que garantam exclusivamente os riscos de morte ou invalidez (n.º 2 do artigo 87.º do Código do IRS)",
  },
  {
    value: "606",
    label:
      "Despesas com a educação e reabilitação do sujeito passivo ou dependentes deficientes (n.º 2 do artigo 87.º do Código do IRS)",
  },
  {
    value: "607",
    label:
      "Encargos suportados com a reabilitação de imóveis arrendados ou localizados em áreas de reabilitação - (n.º 4 do artigo 71.º do EBF)",
  },
  {
    value: "608",
    label:
      "Donativos a igrejas e a instituições religiosas (n.º 2 do artigo 63.º do EBF)",
  },
  {
    value: "609",
    label:
      "Mecenato científico - Donativos a fundações, instituições de ensino superior, laboratórios, órgãos de comunicação social, etc., - de natureza científica - (n.º 3 do artigo 62.º-A do EBF)",
  },
  {
    value: "610",
    label:
      "Mecenato científico - Contratos plurianuais - Donativos a fundações, instituições de ensino superior, laboratórios, órgãos de comunicação social, etc., - de natureza científica - (n.ºs 3 e 4 do artigo 62.º-A do EBF)",
  },
  {
    value: "611",
    label:
      "Mecenato ambiental / desportivo / educacional - Donativos concedidos no âmbito do mecenato ambiental, desportivo e educacional (n.º 6 do artigo 62.º do EBF) - Anos de 2017 e anteriores",
  },
  {
    value: "612",
    label:
      "Mecenato ambiental / desportivo / educacional - Contratos plurianuais - Donativos concedidos no âmbito do mecenato ambiental, desportivo e educacional, atribuídos ao abrigo de contratos plurianuais (n.ºs 6 e 7 do artigo 62.º do EBF) - Anos de 2017 e anteriores",
  },
  {
    value: "613",
    label:
      "Mecenato social - Donativos atribuídos no âmbito do mecenato social (n.º 3 do artigo 62.º do EBF)",
  },
  {
    value: "614",
    label:
      "Mecenato social de apoio especial - Donativos atribuídos no âmbito do mecenato social, para apoio à infância, tratamento de toxicodependentes, criação de oportunidades de trabalho, bem como creches, lactários e jardins-de-infância legalmente reconhecidos pelo ministério competente e organismos públicos de produção artística (n.º 4 e alínea c) do n.º 7 do artigo 62.º do EBF)",
  },
  {
    value: "615",
    label:
      "Mecenato familiar - Donativos concedidos no âmbito de mecenato familiar (n.º 5 do artigo 62.º do EBF)",
  },
  {
    value: "616",
    label:
      "Mecenato cultural - Donativos concedidos no âmbito de mecenato cultural (n.º 5 do artigo 62.º- B do EBF)",
  },
  {
    value: "617",
    label:
      "Mecenato cultural - Contratos plurianuais - Donativos concedidos no âmbito de mecenato cultural (nº.6 do artigo 62º-B do EBF)",
  },
  {
    value: "618",
    label:
      "Estado - Mecenato científico - Donativos ao Estado, Regiões Autónomas, autarquias locais, associações de municípios e de freguesias e fundações - (n.º 2 do artigo 62.º-A do EBF)",
  },
  {
    value: "619",
    label:
      "Estado - Mecenato científico - Contratos plurianuais - Donativos ao Estado, Regiões Autónomas, autarquias locais, associações de municípios e de freguesias e fundações - (n.ºs 2 e 4 do artigo 62.º-A do EBF)",
  },
  {
    value: "620",
    label:
      "Estado - Mecenato ambiental, desportivo e educacional - Donativos ao Estado, Regiões Autónomas, autarquias locais, associações de municípios e de freguesias e fundações - de natureza cultural, ambiental, desportiva e educacional (n.ºs 1 e 2 do artigo 62.º do EBF)",
  },
  {
    value: "621",
    label:
      "Estado - Mecenato ambiental, desportivo e educacional - contratos plurianuais - Donativos ao Estado, Regiões Autónomas, autarquias locais, associações de municípios e de freguesias e fundações - de natureza cultural, ambiental, desportivo e educacional com contratos plurianuais (n.ºs 1 e 2 do artigo 62.º do EBF)",
  },
  {
    value: "622",
    label:
      "Estado - Mecenato social - Donativos ao Estado, Regiões Autónomas, autarquias locais, SPMS - Serviços Partilhados do Ministério da Saúde, EPE, Entidades Hospitalares, EPE (ano de 2020), associações de municípios e de freguesias e fundações, bem como creches, lactários, jardins-de-infância e organismos públicos de produção artística - de natureza social [n.ºs 1 e 2 e alínea c) do n.º 7 do artigo 62.º do EBF]",
  },
  {
    value: "623",
    label:
      "Estado - Mecenato familiar - Donativos ao Estado, Regiões Autónomas, autarquias locais, associações de municípios e de freguesias e fundações (n.º 5 do artigo 62.º do EBF)",
  },
  {
    value: "624",
    label:
      "Estado - Mecenato cultural - Donativos ao Estado, Regiões Autónomas, autarquias locais associações de municípios e de freguesias e fundações (n.º 4 do artigo 62.º- B do EBF)",
  },
  {
    value: "625",
    label:
      "Estado - Mecenato cultural - contratos plurianuais - Donativos ao Estado, Regiões Autónomas, autarquias locais; associações de municípios e de freguesias e fundações (n.º 6 do artigo 62.º- B do EBF)",
  },
  {
    value: "626",
    label: "Programa Semente (artigo 43.º-A do EBF) - anos de 2017 a 2021",
  },
  {
    value: "627",
    label: "Investidores de Capital de Risco (artigo 32.º-A do EBF)",
  },
  {
    value: "628",
    label:
      "Mecenato ambiental / educacional - Donativos concedidos no âmbito do mecenato ambiental e educacional (n.º 6, exceto alíneas d) e e), do artigo 62.º do EBF) - Anos de 2018 e seguintes",
  },
  {
    value: "629",
    label:
      "Mecenato desportivo - Donativos concedidos no âmbito do mecenato desportivo (alíneas d) e e) do n.º 6 do artigo 62.º do EBF) - Anos de 2018 e seguintes",
  },
  {
    value: "630",
    label:
      "Mecenato ambiental / educacional - Contratos plurianuais - Donativos concedidos no âmbito do mecenato ambiental e educacional, atribuídos ao abrigo de contratos plurianuais (n.º 6, exceto alíneas d) e e), e n.º 7 do artigo 62.º do EBF) - Anos de 2018 e seguintes",
  },
  {
    value: "631",
    label:
      "Mecenato desportivo - Contratos plurianuais - Donativos concedidos no âmbito do mecenato desportivo, atribuídos ao abrigo de contratos plurianuais (alíneas d) e e) do n.º 6 e n.º 7 do artigo 62.º do EBF) - Anos de 2018 e seguintes",
  },
  {
    value: "632",
    label:
      "Comemorações do V Centenário da Circum-Navegação - Donativos concedidos à Estrutura de Missão das referidas comemorações (artigo 294.º da Lei n.º 71/2018, de 31 de dezembro - OE para 2019) - Anos de 2019-2022",
  },
  {
    value: "633",
    label:
      "Comemorações do V Centenário da Circum-Navegação - contratos plurianuais - Donativos concedidos à Estrutura de Missão das referidas comemorações (artigo 294.º da Lei n.º 71/2018, de 31 de dezembro - OE para 2019) - Anos de 2019-2022",
  },
  {
    value: "634",
    label:
      "Estrutura de Missão para a Presidência do Conselho da União Europeia em 2021 (n.º 2 do artigo 357.º da Lei n.º 2/2020, de 31 de março - OE para 2020) - Anos de 2020 e 2021",
  },
  {
    value: "635",
    label:
      "Estrutura de Missão para a Presidência do Conselho da União Europeia em 2021 - contratos plurianuais - (n.º 2 do artigo 357.º da Lei n.º 2/2020, de 31 de março - OE para 2020) - Anos de 2020 e 2021",
  },
  {
    value: "636",
    label:
      "Exposição Mundial do Dubai (n.º 3 do artigo 357.º da Lei n.º 2/2020, de 31 de março - OE para 2020) - Anos de 2020 e 2021",
  },
  {
    value: "637",
    label:
      "Exposição Mundial do Dubai - contratos plurianuais - (n.º 3 do artigo 357.º da Lei n.º 2/2020, de 31 de março - OE para 2020) - Anos de 2020 e 2021",
  },
  {
    value: "638",
    label:
      '638 - Jornada Mundial da Juventude - Donativos concedidos a favor da "Fundação JMJ-Lisboa 2023" (artigo 265.º da Lei n.º 24-D/2022, de 30 de dezembro - OE para 2023)',
  },
  {
    value: "639",
    label:
      '639 - Jornada Mundial da Juventude - contratos plurianuais - Donativos concedidos a favor da "Fundação JMJ-Lisboa 2023" (artigo 265.º da Lei n.º 24-D/2022, de 30 de dezembro - OE para 2023)',
  },
  {
    value: "640",
    label:
      "Mecenato Cultural Extraordinário - Ações ou projetos sem conexão direta com território do interior (artigo 397.º da Lei n.º 75-B/2020, de 31 de dezembro - OE para 2021)",
  },
  {
    value: "641",
    label:
      "Mecenato Cultural Extraordinário - Ações ou projetos sem conexão direta com território do interior - contratos plurianuais - (artigo 397.º da Lei n.º 75-B/2020, de 31 de dezembro - OE para 2021)",
  },
  {
    value: "642",
    label:
      "Mecenato Cultural Extraordinário - Ações ou projetos com conexão direta com território do interior (artigo 397.º da Lei n.º 75-B/2020, de 31 de dezembro - OE para 2021)",
  },
  {
    value: "643",
    label:
      "Mecenato Cultural Extraordinário - Ações ou projetos com conexão direta com território do interior - contratos plurianuais - (artigo 397.º da Lei n.º 75-B/2020, de 31 de dezembro - OE para 2021)",
  },
  {
    value: "644",
    label:
      "Produtos Individuais de reforma pan-europeus (n.º 11 do artigo 21.º do EBF)",
  },
];

export const CatalogoPaises = [
  { value: "", label: "Selecione" },
  { value: "4", label: "Afeganistão" },
  { value: "710", label: "África do Sul" },
  { value: "248", label: "Alanda" },
  { value: "8", label: "Albânia" },
  { value: "276", label: "Alemanha" },
  { value: "20", label: "Andorra" },
  { value: "24", label: "Angola" },
  { value: "660", label: "Anguilla" },
  { value: "807", label: "Antiga República Jugoslava da Macedónia" },
  { value: "28", label: "Antígua e Barbuda" },
  { value: "682", label: "Arábia Saudita" },
  { value: "12", label: "Argélia" },
  { value: "32", label: "Argentina" },
  { value: "51", label: "Arménia" },
  { value: "533", label: "Aruba" },
  { value: "36", label: "Austrália" },
  { value: "40", label: "Áustria" },
  { value: "31", label: "Azerbaijão" },
  { value: "44", label: "Baamas" },
  { value: "50", label: "Bangladesh" },
  { value: "52", label: "Barbados" },
  { value: "48", label: "Barém" },
  { value: "56", label: "Bélgica" },
  { value: "84", label: "Belize" },
  { value: "204", label: "Benim" },
  { value: "60", label: "Bermudas" },
  { value: "112", label: "Bielorrússia" },
  { value: "68", label: "Bolívia" },
  { value: "535", label: "Bonaire, Saint Eustatius e Saba" },
  { value: "70", label: "Bósnia-Herzegovina" },
  { value: "72", label: "Botsuana" },
  { value: "76", label: "Brasil" },
  { value: "96", label: "Brunei" },
  { value: "100", label: "Bulgária" },
  { value: "854", label: "Burquina Faso" },
  { value: "108", label: "Burundi" },
  { value: "64", label: "Butão" },
  { value: "132", label: "Cabo Verde" },
  { value: "120", label: "Camarões" },
  { value: "116", label: "Camboja" },
  { value: "124", label: "Canadá" },
  { value: "634", label: "Catar" },
  { value: "398", label: "Cazaquistão" },
  { value: "148", label: "Chade" },
  { value: "152", label: "Chile" },
  { value: "156", label: "China" },
  { value: "196", label: "Chipre" },
  { value: "170", label: "Colômbia" },
  { value: "174", label: "Comores" },
  { value: "178", label: "Congo" },
  { value: "408", label: "Coreia do Norte" },
  { value: "410", label: "Coreia do Sul" },
  { value: "384", label: "Costa do Marfim" },
  { value: "188", label: "Costa Rica" },
  { value: "191", label: "Croácia" },
  { value: "192", label: "Cuba" },
  { value: "531", label: "Curaçau" },
  { value: "208", label: "Dinamarca" },
  { value: "212", label: "Dominica" },
  { value: "818", label: "Egito" },
  { value: "784", label: "Emirados Árabes Unidos" },
  { value: "218", label: "Equador" },
  { value: "232", label: "Eritreia" },
  { value: "703", label: "Eslováquia" },
  { value: "705", label: "Eslovénia" },
  { value: "724", label: "Espanha" },
  { value: "275", label: "Estado da Palestina" },
  { value: "840", label: "Estados Unidos da América" },
  { value: "233", label: "Estónia" },
  { value: "231", label: "Etiópia" },
  { value: "234", label: "Faroé" },
  { value: "242", label: "Fiji" },
  { value: "608", label: "Filipinas" },
  { value: "246", label: "Finlândia" },
  { value: "250", label: "França" },
  { value: "266", label: "Gabão" },
  { value: "270", label: "Gâmbia" },
  { value: "288", label: "Gana" },
  { value: "268", label: "Geórgia" },
  { value: "292", label: "Gibraltar" },
  { value: "308", label: "Granada" },
  { value: "300", label: "Grécia" },
  { value: "304", label: "Gronelândia" },
  { value: "312", label: "Guadalupe" },
  { value: "316", label: "Guame" },
  { value: "320", label: "Guatemala" },
  { value: "831", label: "Guernesey" },
  { value: "328", label: "Guiana" },
  { value: "254", label: "Guiana Francesa" },
  { value: "324", label: "Guiné" },
  { value: "226", label: "Guiné Equatorial" },
  { value: "624", label: "Guiné-Bissau" },
  { value: "332", label: "Haiti" },
  { value: "340", label: "Honduras" },
  { value: "344", label: "Hong-Kong" },
  { value: "348", label: "Hungria" },
  { value: "887", label: "Iémen" },
  { value: "833", label: "Ilha de Man" },
  { value: "162", label: "Ilha do Natal" },
  { value: "574", label: "Ilha Norfolk" },
  { value: "980", label: "Ilha de Queshm (Irão)" },
  { value: "136", label: "Ilhas Caimão" },
  { value: "184", label: "Ilhas Cook" },
  { value: "166", label: "Ilhas dos Cocos" },
  { value: "238", label: "Ilhas Falkland (Malvinas)" },
  { value: "580", label: "Ilhas Marianas do Norte" },
  { value: "584", label: "Ilhas Marshall" },
  { value: "612", label: "Ilhas Pitcairn" },
  { value: "90", label: "Ilhas Salomão" },
  { value: "796", label: "Ilhas Turcas e Caicos" },
  { value: "92", label: "Ilhas Virgens Britânicas" },
  { value: "850", label: "Ilhas Virgens dos Estados Unidos" },
  { value: "356", label: "Índia" },
  { value: "360", label: "Indonésia" },
  { value: "364", label: "Irão" },
  { value: "368", label: "Iraque" },
  { value: "372", label: "Irlanda" },
  { value: "352", label: "Islândia" },
  { value: "376", label: "Israel" },
  { value: "380", label: "Itália" },
  { value: "388", label: "Jamaica" },
  { value: "392", label: "Japão" },
  { value: "832", label: "Jersey" },
  { value: "262", label: "Jibuti" },
  { value: "400", label: "Jordânia" },
  { value: "414", label: "Koweit" },
  { value: "981", label: "Labuán (Malásia)" },
  { value: "418", label: "Laos" },
  { value: "426", label: "Lesoto" },
  { value: "428", label: "Letónia" },
  { value: "422", label: "Líbano" },
  { value: "430", label: "Libéria" },
  { value: "434", label: "Líbia" },
  { value: "438", label: "Liechtenstein" },
  { value: "440", label: "Lituânia" },
  { value: "442", label: "Luxemburgo" },
  { value: "446", label: "Macau" },
  { value: "450", label: "Madagáscar" },
  { value: "175", label: "Maiote" },
  { value: "458", label: "Malásia" },
  { value: "454", label: "Maláui" },
  { value: "462", label: "Maldivas" },
  { value: "466", label: "Mali" },
  { value: "470", label: "Malta" },
  { value: "504", label: "Marrocos" },
  { value: "474", label: "Martinica" },
  { value: "480", label: "Maurícia" },
  { value: "478", label: "Mauritânia" },
  { value: "484", label: "México" },
  { value: "104", label: "Mianmar/Birmânia" },
  { value: "583", label: "Micronésia" },
  { value: "508", label: "Moçambique" },
  { value: "498", label: "Moldávia" },
  { value: "492", label: "Mónaco" },
  { value: "496", label: "Mongólia" },
  { value: "500", label: "Monserrate" },
  { value: "499", label: "Montenegro" },
  { value: "516", label: "Namíbia" },
  { value: "520", label: "Nauru" },
  { value: "524", label: "Nepal" },
  { value: "558", label: "Nicarágua" },
  { value: "562", label: "Níger" },
  { value: "566", label: "Nigéria" },
  { value: "570", label: "Niuê" },
  { value: "578", label: "Noruega" },
  { value: "540", label: "Nova Caledónia" },
  { value: "554", label: "Nova Zelândia" },
  { value: "512", label: "Omã" },
  { value: "528", label: "Países Baixos" },
  { value: "585", label: "Palau" },
  { value: "591", label: "Panamá" },
  { value: "598", label: "Papua-Nova Guiné" },
  { value: "586", label: "Paquistão" },
  { value: "600", label: "Paraguai" },
  { value: "604", label: "Peru" },
  { value: "258", label: "Polinésia Francesa" },
  { value: "616", label: "Polónia" },
  { value: "620", label: "Portugal" },
  { value: "630", label: "Porto Rico" },
  { value: "404", label: "Quénia" },
  { value: "417", label: "Quirguistão" },
  { value: "296", label: "Quiribáti" },
  { value: "826", label: "Reino Unido" },
  { value: "140", label: "República Centro-Africana" },
  { value: "203", label: "República Checa" },
  { value: "180", label: "República Democrática do Congo" },
  { value: "214", label: "República Dominicana" },
  { value: "638", label: "Reunião" },
  { value: "642", label: "Roménia" },
  { value: "646", label: "Ruanda" },
  { value: "643", label: "Rússia" },
  { value: "663", label: "Saint-Martin (Francesa)" },
  { value: "222", label: "Salvador" },
  { value: "882", label: "Samoa" },
  { value: "16", label: "Samoa Americana" },
  {
    value: "654",
    label: "Santa Helena, Ascensão e Tristão da Cunha",
  },
  { value: "662", label: "Santa Lúcia" },
  { value: "336", label: "Santa Sé / Estado da Cidade do Vaticano" },
  { value: "652", label: "São Bartolomeu" },
  { value: "659", label: "São Cristóvão e Neves" },
  { value: "674", label: "São Marinho" },
  { value: "666", label: "São Pedro e Miquelão" },
  { value: "678", label: "São Tomé e Príncipe" },
  { value: "670", label: "São Vicente e Granadinas" },
  { value: "732", label: "Sara Ocidental" },
  { value: "690", label: "Seicheles" },
  { value: "686", label: "Senegal" },
  { value: "694", label: "Serra Leoa" },
  { value: "688", label: "Sérvia" },
  { value: "702", label: "Singapura" },
  { value: "534", label: "Sint Maarten (Holandesa)" },
  { value: "760", label: "Síria" },
  { value: "706", label: "Somália" },
  { value: "144", label: "Sri Lanca" },
  { value: "748", label: "Suazilândia" },
  { value: "729", label: "Sudão" },
  { value: "728", label: "Sudão do Sul" },
  { value: "752", label: "Suécia" },
  { value: "756", label: "Suíça" },
  { value: "740", label: "Suriname" },
  { value: "744", label: "Svalbard e Jan Mayen" },
  { value: "764", label: "Tailândia" },
  { value: "158", label: "Taiwan" },
  { value: "762", label: "Tajiquistão" },
  { value: "834", label: "Tanzânia" },
  { value: "626", label: "Timor-Leste" },
  { value: "768", label: "Togo" },
  { value: "776", label: "Tonga" },
  { value: "772", label: "Toquelau" },
  { value: "780", label: "Trindade e Tobago" },
  { value: "788", label: "Tunísia" },
  { value: "795", label: "Turquemenistão" },
  { value: "792", label: "Turquia" },
  { value: "798", label: "Tuvalu" },
  { value: "804", label: "Ucrânia" },
  { value: "800", label: "Uganda" },
  { value: "858", label: "Uruguai" },
  { value: "860", label: "Usbequistão" },
  { value: "548", label: "Vanuatu" },
  { value: "862", label: "Venezuela" },
  { value: "704", label: "Vietname" },
  { value: "876", label: "Wallis e Futuna" },
  { value: "894", label: "Zâmbia" },
  { value: "716", label: "Zimbabué" },
];

export const CatalogoPaisesEN = [
  { value: "", label: "Select" },
  { value: "4", label: "Afghanistan" },
  { value: "710", label: "South Africa" },
  { value: "248", label: "Aland Islands" },
  { value: "8", label: "Albania" },
  { value: "276", label: "Germany" },
  { value: "20", label: "Andorra" },
  { value: "24", label: "Angola" },
  { value: "660", label: "Anguilla" },
  { value: "807", label: "North Macedonia" },
  { value: "28", label: "Antigua and Barbuda" },
  { value: "682", label: "Saudi Arabia" },
  { value: "12", label: "Algeria" },
  { value: "32", label: "Argentina" },
  { value: "51", label: "Armenia" },
  { value: "533", label: "Aruba" },
  { value: "36", label: "Australia" },
  { value: "40", label: "Austria" },
  { value: "31", label: "Azerbaijan" },
  { value: "44", label: "Bahamas" },
  { value: "50", label: "Bangladesh" },
  { value: "52", label: "Barbados" },
  { value: "48", label: "Bahrain" },
  { value: "56", label: "Belgium" },
  { value: "84", label: "Belize" },
  { value: "204", label: "Benin" },
  { value: "60", label: "Bermuda" },
  { value: "112", label: "Belarus" },
  { value: "68", label: "Bolivia" },
  { value: "535", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "70", label: "Bosnia and Herzegovina" },
  { value: "72", label: "Botswana" },
  { value: "76", label: "Brazil" },
  { value: "96", label: "Brunei" },
  { value: "100", label: "Bulgaria" },
  { value: "854", label: "Burkina Faso" },
  { value: "108", label: "Burundi" },
  { value: "64", label: "Bhutan" },
  { value: "132", label: "Cape Verde" },
  { value: "120", label: "Cameroon" },
  { value: "116", label: "Cambodia" },
  { value: "124", label: "Canada" },
  { value: "634", label: "Qatar" },
  { value: "398", label: "Kazakhstan" },
  { value: "148", label: "Chad" },
  { value: "152", label: "Chile" },
  { value: "156", label: "China" },
  { value: "196", label: "Cyprus" },
  { value: "170", label: "Colombia" },
  { value: "174", label: "Comoros" },
  { value: "178", label: "Congo" },
  { value: "408", label: "North Korea" },
  { value: "410", label: "South Korea" },
  { value: "384", label: "Ivory Coast" },
  { value: "188", label: "Costa Rica" },
  { value: "191", label: "Croatia" },
  { value: "192", label: "Cuba" },
  { value: "531", label: "Curaçao" },
  { value: "208", label: "Denmark" },
  { value: "212", label: "Dominica" },
  { value: "818", label: "Egypt" },
  { value: "784", label: "United Arab Emirates" },
  { value: "218", label: "Ecuador" },
  { value: "232", label: "Eritrea" },
  { value: "703", label: "Slovakia" },
  { value: "705", label: "Slovenia" },
  { value: "724", label: "Spain" },
  { value: "275", label: "State of Palestine" },
  { value: "840", label: "United States" },
  { value: "233", label: "Estonia" },
  { value: "231", label: "Ethiopia" },
  { value: "234", label: "Faroe Islands" },
  { value: "242", label: "Fiji" },
  { value: "608", label: "Philippines" },
  { value: "246", label: "Finland" },
  { value: "250", label: "France" },
  { value: "266", label: "Gabon" },
  { value: "270", label: "Gambia" },
  { value: "288", label: "Ghana" },
  { value: "268", label: "Georgia" },
  { value: "292", label: "Gibraltar" },
  { value: "308", label: "Grenada" },
  { value: "300", label: "Greece" },
  { value: "304", label: "Greenland" },
  { value: "312", label: "Guadeloupe" },
  { value: "316", label: "Guam" },
  { value: "320", label: "Guatemala" },
  { value: "831", label: "Guernsey" },
  { value: "328", label: "Guyana" },
  { value: "254", label: "French Guiana" },
  { value: "324", label: "Guinea" },
  { value: "226", label: "Equatorial Guinea" },
  { value: "624", label: "Guinea-Bissau" },
  { value: "332", label: "Haiti" },
  { value: "340", label: "Honduras" },
  { value: "344", label: "Hong Kong" },
  { value: "348", label: "Hungary" },
  { value: "887", label: "Yemen" },
  { value: "833", label: "Isle of Man" },
  { value: "162", label: "Christmas Island" },
  { value: "574", label: "Norfolk Island" },
  { value: "980", label: "Qeshm Island (Iran)" },
  { value: "136", label: "Cayman Islands" },
  { value: "184", label: "Cook Islands" },
  { value: "166", label: "Cocos (Keeling) Islands" },
  { value: "238", label: "Falkland Islands (Malvinas)" },
  { value: "580", label: "Northern Mariana Islands" },
  { value: "584", label: "Marshall Islands" },
  { value: "612", label: "Pitcairn Islands" },
  { value: "90", label: "Solomon Islands" },
  { value: "796", label: "Turks and Caicos Islands" },
  { value: "92", label: "British Virgin Islands" },
  { value: "850", label: "United States Virgin Islands" },
  { value: "356", label: "India" },
  { value: "360", label: "Indonesia" },
  { value: "364", label: "Iran" },
  { value: "368", label: "Iraq" },
  { value: "372", label: "Ireland" },
  { value: "352", label: "Iceland" },
  { value: "376", label: "Israel" },
  { value: "380", label: "Italy" },
  { value: "388", label: "Jamaica" },
  { value: "392", label: "Japan" },
  { value: "832", label: "Jersey" },
  { value: "262", label: "Djibouti" },
  { value: "400", label: "Jordan" },
  { value: "414", label: "Kuwait" },
  { value: "981", label: "Labuan (Malaysia)" },
  { value: "418", label: "Laos" },
  { value: "426", label: "Lesotho" },
  { value: "428", label: "Latvia" },
  { value: "422", label: "Lebanon" },
  { value: "430", label: "Liberia" },
  { value: "434", label: "Libya" },
  { value: "438", label: "Liechtenstein" },
  { value: "440", label: "Lithuania" },
  { value: "442", label: "Luxembourg" },
  { value: "446", label: "Macao" },
  { value: "450", label: "Madagascar" },
  { value: "175", label: "Mayotte" },
  { value: "458", label: "Malaysia" },
  { value: "454", label: "Malawi" },
  { value: "462", label: "Maldives" },
  { value: "466", label: "Mali" },
  { value: "470", label: "Malta" },
  { value: "504", label: "Morocco" },
  { value: "474", label: "Martinique" },
  { value: "480", label: "Mauritius" },
  { value: "478", label: "Mauritania" },
  { value: "484", label: "Mexico" },
  { value: "104", label: "Myanmar" },
  { value: "583", label: "Micronesia" },
  { value: "508", label: "Mozambique" },
  { value: "498", label: "Moldova" },
  { value: "492", label: "Monaco" },
  { value: "496", label: "Mongolia" },
  { value: "500", label: "Montserrat" },
  { value: "499", label: "Montenegro" },
  { value: "516", label: "Namibia" },
  { value: "520", label: "Nauru" },
  { value: "524", label: "Nepal" },
  { value: "558", label: "Nicaragua" },
  { value: "562", label: "Niger" },
  { value: "566", label: "Nigeria" },
  { value: "570", label: "Niue" },
  { value: "578", label: "Norway" },
  { value: "540", label: "New Caledonia" },
  { value: "554", label: "New Zealand" },
  { value: "512", label: "Oman" },
  { value: "528", label: "Netherlands" },
  { value: "585", label: "Palau" },
  { value: "591", label: "Panama" },
  { value: "598", label: "Papua New Guinea" },
  { value: "586", label: "Pakistan" },
  { value: "600", label: "Paraguay" },
  { value: "604", label: "Peru" },
  { value: "258", label: "French Polynesia" },
  { value: "616", label: "Poland" },
  { value: "620", label: "Portugal" },
  { value: "630", label: "Puerto Rico" },
  { value: "404", label: "Kenya" },
  { value: "417", label: "Kyrgyzstan" },
  { value: "296", label: "Kiribati" },
  { value: "826", label: "United Kingdom" },
  { value: "140", label: "Central African Republic" },
  { value: "203", label: "Czech Republic" },
  { value: "180", label: "Democratic Republic of the Congo" },
  { value: "214", label: "Dominican Republic" },
  { value: "638", label: "Réunion" },
  { value: "642", label: "Romania" },
  { value: "646", label: "Rwanda" },
  { value: "643", label: "Russia" },
  { value: "663", label: "Saint Martin (French part)" },
  { value: "222", label: "El Salvador" },
  { value: "882", label: "Samoa" },
  { value: "16", label: "American Samoa" },
  { value: "654", label: "Saint Helena, Ascension and Tristan da Cunha" },
  { value: "662", label: "Saint Lucia" },
  { value: "336", label: "Holy See (Vatican City State)" },
  { value: "652", label: "Saint Barthélemy" },
  { value: "659", label: "Saint Kitts and Nevis" },
  { value: "674", label: "San Marino" },
  { value: "666", label: "Saint Pierre and Miquelon" },
  { value: "678", label: "Sao Tome and Principe" },
  { value: "670", label: "Saint Vincent and the Grenadines" },
  { value: "732", label: "Western Sahara" },
  { value: "690", label: "Seychelles" },
  { value: "686", label: "Senegal" },
  { value: "694", label: "Sierra Leone" },
  { value: "688", label: "Serbia" },
  { value: "702", label: "Singapore" },
  { value: "534", label: "Sint Maarten (Dutch part)" },
  { value: "760", label: "Syria" },
  { value: "706", label: "Somalia" },
  { value: "144", label: "Sri Lanka" },
  { value: "748", label: "Eswatini" },
  { value: "729", label: "Sudan" },
  { value: "728", label: "South Sudan" },
  { value: "752", label: "Sweden" },
  { value: "756", label: "Switzerland" },
  { value: "740", label: "Suriname" },
  { value: "744", label: "Svalbard and Jan Mayen" },
  { value: "764", label: "Thailand" },
  { value: "158", label: "Taiwan" },
  { value: "762", label: "Tajikistan" },
  { value: "834", label: "Tanzania" },
  { value: "626", label: "Timor-Leste" },
  { value: "768", label: "Togo" },
  { value: "776", label: "Tonga" },
  { value: "772", label: "Tokelau" },
  { value: "780", label: "Trinidad and Tobago" },
  { value: "788", label: "Tunisia" },
  { value: "795", label: "Turkmenistan" },
  { value: "792", label: "Turkey" },
  { value: "798", label: "Tuvalu" },
  { value: "804", label: "Ukraine" },
  { value: "800", label: "Uganda" },
  { value: "858", label: "Uruguay" },
  { value: "860", label: "Uzbekistan" },
  { value: "548", label: "Vanuatu" },
  { value: "862", label: "Venezuela" },
  { value: "704", label: "Vietnam" },
  { value: "876", label: "Wallis and Futuna" },
  { value: "894", label: "Zambia" },
  { value: "716", label: "Zimbabwe" },
];

export const CatalogoCodigosRendimentoJ8A = [
  { value: "", label: "Selecione" },
  { value: "E01", label: "Royalties e Assistência Técnica" },
  {
    value: "E10",
    label: "Dividendos ou lucros - com retenção em Portugal",
  },
  {
    value: "E11",
    label: "Dividendos ou lucros - sem retenção em Portugal",
  },
  {
    value: "E20",
    label:
      "Rendimentos de valores mobiliários, com retenção em Portugal (exceto E10, E23, E24)",
  },
  {
    value: "E21",
    label: "Juros sem retenção em Portugal (exceto E22, E23, E24)",
  },
  {
    value: "E22",
    label:
      "Outros rendimentos de capitais sem retenção (exceto E11, E21, E23, E24)",
  },
  {
    value: "E23",
    label:
      "Rendimentos abrangidos pela Diretiva da Poupança 2003/48/CE Países/Territórios - Período de transição - artigo 10.º da diretiva - Aplicável aos anos de 2015 e 2016",
  },
  {
    value: "E24",
    label:
      "Rendimentos abrangidos pela Diretiva da Poupança 2003/48/CE Restantes países não abrangidos pelo período de transição - artigo 10.º da diretiva - Aplicável aos anos de 2015 a 2017",
  },
  { value: "E25", label: "Rendimentos de capitais (criptoativos)" },
  {
    value: "E99",
    label:
      "Rendimentos de capitais com origem em país, território ou região com regime fiscal claramente mais favorável",
  },
];
export const CatalogoCodigosRendimentoJ9A = [
  {
    label: "Selecione",
    value: "",
  },
  {
    label: "Alienação onerosa de ações/partes sociais",
    value: "G01",
  },
  {
    label: "Alienação onerosa de quotas",
    value: "G02",
  },
  {
    label: "Remição e amortização com redução de capital de partes sociais",
    value: "G03",
  },
  {
    label:
      "Extinção ou entrega de partes sociais das sociedades fundidas, cindidas ou adquiridas no âmbito de operações de fusão, cisão ou permuta de partes sociais",
    value: "G04",
  },
  {
    label:
      "Valor atribuído em resultado da partilha, bem como em resultado da liquidação, revogação ou extinção de estruturas fiduciárias aos sujeitos passivos que as constituíram, nos termos dos artigos 81.º e 82.º do Código do IRC",
    value: "G05",
  },
  {
    label:
      "Alienações de partes de capital que tenham por base 50% do valor em imóveis situados no outro Estado contratante",
    value: "G06",
  },
  {
    label:
      "Alienação onerosa ou reembolso de obrigações e outros títulos de dívida",
    value: "G10",
  },
  {
    label:
      "Resgates ou alienação de unidades de participação ou liquidação de fundos de investimento",
    value: "G20",
  },
  {
    label:
      "Alienação onerosa de criptoativos que constituem valores mobiliários",
    value: "G34",
  },
  {
    label: "Alienação onerosa de outros valores mobiliários",
    value: "G90",
  },
];
export const CatalogoCodigosRendimentoJ9B = [
  { value: "", label: "Selecione" },
  {
    value: "G30",
    label:
      "Operações relativas a instrumentos financeiros derivados (entre os quais, opções, futuros, forwards, swaps cambiais, swaps de taxa de juro e divisas e de operações cambiais a prazo), com exceção dos previstos na alínea q) do n.º 2 do artigo 5.º Código do IRS",
  },
  { value: "G31", label: "Warrants autónomos" },
  {
    value: "G32",
    label:
      "Certificados que atribuam direito a receber valor de ativo subjacente",
  },
  {
    value: "G33",
    label:
      "Produtos financeiros complexos quando o risco de perda de capital existe",
  },
  {
    value: "G97",
    label:
      "Alienação onerosa da propriedade intelectual ou industrial ou de experiência adquirida no sector comercial, industrial ou científico, quando o transmitente não seja o seu titular originário",
  },
  {
    value: "G98",
    label:
      "Cessão onerosa de créditos, prestações acessórias e prestações suplementares",
  },
];
